### ISSUE TITLE
Naming and documentation of modular testing modes

### ISSUE THREAD

**Issue by sormuras** [sormuras/junit-platform-maven-plugin#4]
/cc @forax @jodastephen @nicolaiparlog @rfscholte

# Workbench

I need help finding better names for some enumartion constants.

### Table of all modes

```
   *                          main plain    main module   main module
   *                             ---            foo           bar
   *
   *     test plain  ---          0              2             2
   *
   *     test module foo          1              3             4
   *
   *     test module bar          1              4             3
   *
   *     0 = CLASSIC
   *     1 = MAIN_CLASSIC_TEST_MODULE           (black-box test) // CLASSIC_MODULAR_TEST
   *     2 = MAIN_MODULE_TEST_CLASSIC           (white-box test) // MODULAR_CLASSIC_TEST
   *     3 = MAIN_MODULE_TEST_MODULE_SAME_NAME  (white-box test) // MODULAR_PATCHED_TEST
   *     4 = MODULAR                            (black-box test) // MODULAR_BLACKBOX_TEST
```

The following code snippet examines two related modules that may be present in a typical Maven [*1] project in the _main_ and _test_ source sets. The modules are referred to by their names. `null` as name is interpreted as either there is no such source set or the source set doesn't contain a module.

https://github.com/sormuras/junit-platform-maven-plugin/blob/350c93cf01b02c1519f2f2f3f1a7f9d1d747b74c/src/main/java/de/sormuras/junit/platform/maven/plugin/Modules.java#L92-L106

_*1_  The actual build tool does not matter, but provides a well-known context here.

# Tasks

- [ ] Find missing and interesting modes, interesting from a test run perspective.
- [ ] Find better and concise names for: `MAIN_CLASSIC_TEST_MODULE`, `MAIN_MODULE_TEST_CLASSIC`, and `MAIN_MODULE_TEST_MODULE_SAME_NAME`
- [ ] Is [`Barrier`](https://github.com/sormuras/junit-platform-maven-plugin/blob/350c93cf01b02c1519f2f2f3f1a7f9d1d747b74c/src/main/java/de/sormuras/junit/platform/maven/plugin/Modules.java#L27-L34) a technically good name for its purpose?
- [ ] Polish and extend the Javadoc where needed.

**Comment by rfscholte** [comment]
Out of curiosity: does this mean we'll finally have 3 classloaders to ensure classes don't leak? That is for jupiter-engine, main classes and test classes?

**Comment by sormuras** [comment]
Hm? Which classes leak where? When compiling main and or tests, when running tests? Do have a test-case or issue for me to see where the leak happens?

**Comment by rfscholte** [comment]
I created one a long time ago with @britter at ApacheCon, I think he still has it somewhere. Right now everything is one 1 classpath, which means that "main" code can access the testclasses and engine, which is not desired. Same counts for "test" code: it should not be able to access engine code. 
I use the word "access" on purpose, because maven scopes prevent you from doing this during compilation, but it is still possible via reflection.

**Comment by sormuras** [comment]
Ah, now I get it. Moving this classloader issue to a different issue: https://github.com/sormuras/junit-platform-maven-plugin/issues/6

**Comment by forax** [comment]
Robert,
in a modular world, you should not need to use classloaders for doing isolation, ModuleLayers should be enough.

**Comment by sormuras** [comment]
Fixed caption of #6 to reflect Rémis note. Please follow up on the topic there. Thanks.

**Comment by rfscholte** [comment]
Remi, it should be either separe classloaders or module layers. Right now everything is just put on 1 classpath/modulepath. This is one of the main reasons why with Maven there's only 1 artifact version for all scopes, you cannot specify a different version for test compared to compile.

**Comment by jodastephen** [comment]
The names are OK. Another possible set of names:

* CLASSIC
* CLASSIC_MODULAR_TEST
* MODULAR_CLASSIC_TEST 
* MODULAR_PATCHED_TEST 
* MODULAR_BLACKBOX_TEST

Please ensure that `<excludes>` is taken into account when determining if `module-info` exists.

**Comment by sormuras** [comment]
### Table of all modes

```
   *                          main plain    main module   main module
   *                             ---            foo           bar
   *
   *     test plain  ---          0              2             2
   *
   *     test module foo          1              3             4
   *
   *     test module bar          1              4             3
   *
   *     0 = CLASSIC
   *     1 = MAIN_CLASSIC_TEST_MODULE           (black-box test) // CLASSIC_MODULAR_TEST
   *     2 = MAIN_MODULE_TEST_CLASSIC           (white-box test) // MODULAR_CLASSIC_TEST
   *     3 = MAIN_MODULE_TEST_MODULE_SAME_NAME  (white-box test) // MODULAR_PATCHED_TEST
   *     4 = MODULAR                            (black-box test) // MODULAR_BLACKBOX_TEST
```

@rfscholte `testCompile` throws an `UnsupportedOperationException` for mode 1, if the main source set is not empty. I think, it is no longer needed. Just put the main output directory on the class-path and be good. Perhaps emitting a warning here is okay.

[1] https://github.com/apache/maven-compiler-plugin/blob/master/src/main/java/org/apache/maven/plugin/compiler/TestCompilerMojo.java#L370-L375

**Comment by sormuras** [comment]
Mh, i'd rather have two different test roots to achieve this separation of test concerns:

```
src/
  main/ module foo
  test/ open module foo     // mode 3 (or if you omit the test module-info.java: mode 2)
  test-modular/ module bar  // mode 4
```
And then invoke `maven-compiler-plugin` + and any `test` plugin twice. This needs some extra configuration setup in your `pom.xml` which might move into standards, some day.

Or, keep the structure as it is and introduce an "integration tests" source tree which is harvested by the `maven-invoker-plugin`:
```
src/
  main/ module foo
  test/ open module foo  // mode 3 (or if you omit the test module-info.java: mode 2)
src/
  integration/
    modular/
      test/ module bar // mode 4 "requires foo"
    other-setupt/
      test/ module other.setup // mode 4 "requires foo"
```

**Comment by sormuras** [comment]
The advantage of the "integration tests" approach is that your test projects refer to packaged artifact "foo". You get, for example, correct multi-release jar behaviour for granted.

**Comment by sormuras** [comment]
Created such an integration test project here: https://github.com/sormuras/sandbox/tree/master/sors-modular-testing-blueprint

If only IDE's supported test modules... or ignores them from compilation/error detection.

**Comment by sormuras** [comment]
Final version
```
 *                          main plain    main module   main module
 *                             ---            foo           bar
 *
 *     test plain  ---          0              3             3
 *
 *     test module foo          1              2             1
 *
 *     test module bar          1              1             2
 *
 *     0 = CLASSIC                      // no modules available
 *     1 = MODULAR                      // main lacks module, test 'module any'
 *     1 = MODULAR                      // main 'module foo', test 'module bar'
 *     2 = MODULAR_PATCHED_TEST_COMPILE // main 'module foo', test 'module foo'
 *     3 = MODULAR_PATCHED_TEST_RUNTIME // main 'module foo', test lacks module
```

**Comment by sormuras** [comment]
Merged both "modular" modes to one.
